export enum AMCPermissions {
  VIEW_AMC = 'VIEW_AMC',
  CREATE_AMC = 'CREATE_AMC',
  UPDATE_AMC = 'UPDATE_AMC',
  DELETE_AMC = 'DELETE_AMC',
  RENEW_AMC = 'RENEW_AMC',
  VIEW_AMC_DASHBOARD = 'VIEW_AMC_DASHBOARD',
  MAP_AMC_ASSETS = 'MAP_AMC_ASSETS',
  GENERATE_AMC_PM = 'GENERATE_AMC_PM',
}
