export enum ReliabilityPermissions {
  VIEW_RELIABILITY = 'VIEW_RELIABILITY',
  MANAGE_RELIABILITY = 'MANAGE_RELIABILITY',
  VIEW_FMECA = 'VIEW_FMECA',
  MANAGE_FMECA = 'MANAGE_FMECA',
  VIEW_RCM = 'VIEW_RCM',
  MANAGE_RCM = 'MANAGE_RCM',
}
