export enum ServiceTicketPermissions {
  VIEW_SERVICE_TICKET = 'VIEW_SERVICE_TICKET',
  CREATE_SERVICE_TICKET = 'CREATE_SERVICE_TICKET',
  UPDATE_SERVICE_TICKET = 'UPDATE_SERVICE_TICKET',
  DELETE_SERVICE_TICKET = 'DELETE_SERVICE_TICKET',
  ASSIGN_SERVICE_TICKET = 'ASSIGN_SERVICE_TICKET',
  CLOSE_SERVICE_TICKET = 'CLOSE_SERVICE_TICKET',
  CREATE_SERVICE_TICKET_WORKORDER = 'CREATE_SERVICE_TICKET_WORKORDER',
  VIEW_SERVICE_TICKET_DASHBOARD = 'VIEW_SERVICE_TICKET_DASHBOARD',
}
