export enum ContractType {
  COMPREHENSIVE = 'COMPREHENSIVE',
  NON_COMPREHENSIVE = 'NON_COMPREHENSIVE',
  LABOUR_ONLY = 'LABOUR_ONLY',
  PREVENTIVE_ONLY = 'PREVENTIVE_ONLY',
}

export enum AMCStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  RENEWED = 'RENEWED',
}

export enum VisitStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  MISSED = 'MISSED',
}
