export enum IncidentType {
  SAFETY = 'SAFETY',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  SECURITY = 'SECURITY',
  OPERATIONAL = 'OPERATIONAL',
  FIRE = 'FIRE',
  CHEMICAL = 'CHEMICAL',
  NEAR_MISS = 'NEAR_MISS',
  ELECTRICAL = 'ELECTRICAL',
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  OTHER = 'OTHER',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  CORRECTIVE_ACTION = 'CORRECTIVE_ACTION',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}
