export enum IncidentPermissions {
  VIEW_INCIDENT = 'VIEW_INCIDENT',
  CREATE_INCIDENT = 'CREATE_INCIDENT',
  UPDATE_INCIDENT = 'UPDATE_INCIDENT',
  DELETE_INCIDENT = 'DELETE_INCIDENT',
  INVESTIGATE_INCIDENT = 'INVESTIGATE_INCIDENT',
  CLOSE_INCIDENT = 'CLOSE_INCIDENT',
  CREATE_INCIDENT_WORKORDER = 'CREATE_INCIDENT_WORKORDER',
  VIEW_INCIDENT_DASHBOARD = 'VIEW_INCIDENT_DASHBOARD',
}

export const INCIDENT_CLOSING_ROLES = [
  'ADMIN',
  'SAFETY_OFFICER',
  'MAINTENANCE_MANAGER',
];
